import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Font setup
const inter = Inter({
  subsets: ["latin"],
  display: "swap", // ensures text is visible during font load
  weight: ["400", "500", "600", "700"], // optional: preload needed weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
